language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install -y build-essential cmake fakeroot libboost-program-options-dev libmysqlcppconn-dev txt2man
script: travis_helpers/build_deb_package.sh
